name: AndroidBuild
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Setup Java JDK
        uses: actions/setup-java@3.13.0
        with:
          java-version: '8'
          distribution: 'oracle'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Uplaod a build artifact
        uses: actions/upload-artifact@3.1.3
        with:
          name: AndroidCICDTest.apk
          path: app/build/outputs/apk/debug/app-debug.apk
      
      
